# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Micro blogging platform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Micro blogging platform
  pod 'Alamofire', '~> 5.2'

  target 'Micro blogging platformTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Micro blogging platformUITests' do
    # Pods for testing
  end

end
